### ISSUE TITLE
Reading all events in simtel file?

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/pyeventio#260] opened 2023-08-31 15:25 UTC
https://github.com/cta-observatory/pyeventio/blob/94ebedd3c38ed10810a3aa9eafd734c986fdf56e/src/eventio/simtel/simtelfile.py#L144-L145

The SimTelFile iterator seems to be reading only triggered events.
Is it possible to read also events in which none of the telescopes triggered? Some information (like the true numbers of photoelectrons on the camera) are available and are useful for some purposes.

**Comment by maxnoe** [comment] 2023-08-31 15:29
Yes, there is `iter_mc_events()`:


```
for e in f.iter_mc_events():
    ...
```

which should do that.

There is also this pull request here: https://github.com/cta-observatory/pyeventio/pull/214

Which is open since a long time, but which we should probably finish... maybe you can try it out and give feedback, if it solves your particular issue

**Comment by maxnoe** [comment] 2023-08-31 15:31
I am closing this as a duplicate of #213

**Comment by moralejo** [comment] 2023-08-31 15:31
Ok, thanks!

**Closed by maxnoe** 2023-08-31 15:31 UTC
